=== TeamAutonomousCarOffenburg/TACO_2018/client/base/srcTools/hso/autonomy/tools/util/bundleFramework/xsd/bundleSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	elementFormDefault="qualified">
	
	<!-- Elemente -->
	<!-- Root-Element -->
	<xsd:element name="bundle">
	<xsd:complexType>
		<xsd:sequence>
			<xsd:element name="services" type="serviceDescriptor_list" minOccurs="0" maxOccurs="1"/>
			<xsd:element name="extensionPoints" type="extensionPointDescriptor_list" minOccurs="0" maxOccurs="1"/>
			<xsd:element name="extensions" type="extensionDescriptor_list" minOccurs="0" maxOccurs="1"/>
		</xsd:sequence>
		<xsd:attribute name="name" type="xsd:string" use="required"/>
		<xsd:attribute name="bundleActivator" type="xsd:string" use="required"/>
	</xsd:complexType>
	</xsd:element>
	
	
	
	<!-- Typen -->
	<!-- Listen-Typen -->
	<xsd:complexType name="serviceDescriptor_list">
		<xsd:sequence>
			<xsd:element name="service" type="service_type" minOccurs="0" maxOccurs="unbounded"/>
		</xsd:sequence>
	</xsd:complexType>
	
	<xsd:complexType name="extensionPointDescriptor_list">
		<xsd:sequence>
			<xsd:element name="extensionPoint" type="extensionPoint_type" minOccurs="0" maxOccurs="unbounded"/>
		</xsd:sequence>
	</xsd:complexType>
	
	<xsd:complexType name="extensionDescriptor_list">
		<xsd:sequence>
			<xsd:element name="extension" type="extension_type" minOccurs="0" maxOccurs="unbounded"/>
		</xsd:sequence>
	</xsd:complexType>
	
	<!-- Hilfs-Typen -->
	<xsd:complexType name="service_type">
		<xsd:sequence>
			<xsd:element name="dependency" type="dependency_type" minOccurs="0" maxOccurs="unbounded"/>
		</xsd:sequence>
		<xsd:attribute name="serviceID" type="xsd:string" use="required"/>
		<xsd:attribute name="serviceInterface" type="xsd:string" use="required"/>
	</xsd:complexType>
	
	<xsd:complexType name="extensionPoint_type">
		<xsd:attribute name="extensionPointID" type="xsd:string" use="required"/>
		<xsd:attribute name="extensionPointInterface" type="xsd:string" use="required"/>
	</xsd:complexType>
	
	<xsd:complexType name="extension_type">
		<xsd:sequence>
			<xsd:element name="dependency" type="dependency_type" minOccurs="0" maxOccurs="unbounded"/>
		</xsd:sequence>
		<xsd:attribute name="extensionID" type="xsd:string" use="required"/>
		<xsd:attribute name="extensionPointID" type="xsd:string" use="required"/>
		<xsd:attribute name="extensionPointInterface" type="xsd:string" use="required"/>
	</xsd:complexType>
	
	<xsd:complexType name="dependency_type">
		<xsd:attribute name="serviceID" type="xsd:string" use="required"/>
	</xsd:complexType>
</xsd:schema>

=== TeamAutonomousCarOffenburg/TACO_2018/client/base/srcTools/hso/autonomy/tools/developer/bundles/developer/bundle.xml
<bundle xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		xsi:noNamespaceSchemaLocation="../../../util/bundleFramework/xsd/bundleSchema.xsd"
		name="developer"
		bundleActivator="hso.autonomy.tools.developer.bundles.developer.DeveloperBundleActivator">
	
	<services>
		<service serviceID="developer.windowManager"
				serviceInterface="hso.autonomy.tools.developer.bundles.developer.window.IWindowManager">
		</service>
		<service serviceID="developer.perspectiveManager"
				serviceInterface="hso.autonomy.tools.developer.bundles.developer.perspective.IPerspectiveManager">
		</service>
		<service serviceID="developer.processor"
				serviceInterface="hso.autonomy.tools.developer.bundles.developer.processor.model.IProcessor">
		</service>
		<service serviceID="developer.explorer"
				serviceInterface="hso.autonomy.tools.developer.bundles.developer.explorer.model.IExplorer">
		</service>		
	</services>
	
	<extensionPoints>
		<extensionPoint extensionPointID="developer.perspectiveManager.view"
				extensionPointInterface="hso.autonomy.tools.developer.bundles.developer.perspective.IViewDescriptor" />
		<extensionPoint extensionPointID="developer.windowManager.menu"
				extensionPointInterface="javax.swing.JMenu" />
		<extensionPoint extensionPointID="developer.windowManager.openAction"
				extensionPointInterface="javax.swing.AbstractAction" />
		<extensionPoint	extensionPointID="developer.windowManager.statusObserver"
				extensionPointInterface="hso.autonomy.tools.developer.bundles.developer.window.statusBar.IStatusObserver" />
		<extensionPoint	extensionPointID="developer.windowManager.newWizard"
				extensionPointInterface="hso.autonomy.tools.util.swing.wizard.IWizardDescriptor" />
		<extensionPoint	extensionPointID="developer.windowManager.importWizard"
				extensionPointInterface="hso.autonomy.tools.util.swing.wizard.IWizardDescriptor" />
		<extensionPoint	extensionPointID="developer.windowManager.exportWizard"
				extensionPointInterface="hso.autonomy.tools.util.swing.wizard.IWizardDescriptor" />
		<extensionPoint	extensionPointID="developer.windowManager.runWizard"
				extensionPointInterface="hso.autonomy.tools.util.swing.wizard.IWizardDescriptor" />
	</extensionPoints>
	
	<extensions>
		<!--Views-->
		<extension extensionID="developer.perspectiveManager.view.explorerView"
				extensionPointID="developer.perspectiveManager.view"
				extensionPointInterface="hso.autonomy.tools.developer.bundles.developer.perspective.IViewDescriptor">
		</extension>
		<extension extensionID="developer.perspectiveManager.view.processorView"
				extensionPointID="developer.perspectiveManager.view"
				extensionPointInterface="hso.autonomy.tools.developer.bundles.developer.perspective.IViewDescriptor">
		</extension>
		
		<!--StatusObserver-->
		<extension extensionID="developer.windowManager.statusObserver.processorStatusObserver"
			extensionPointID="developer.windowManager.statusObserver"
			extensionPointInterface="hso.autonomy.tools.developer.bundles.developer.window.statusBar.IStatusObserver">
		</extension>
	</extensions>
</bundle>
